services:
  - type: web
    name: catering-backend
    runtime: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: heroku-php-apache2 public/
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false   # paste your key in Render dashboard
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: ep-flat-lake-adgaraml-pooler.c-2.us-east-1.aws.neon.tech
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: catering
      - key: DB_USERNAME
        value: neondb_owner
      - key: DB_PASSWORD
        sync: false   # set manually in dashboard
      - key: DB_SSLMODE
        value: require
